package micro.Absyn; // Java Package generated by the BNF Converter.

public class EDbl  extends Exp {
  public final Double double_;
  public EDbl(Double p1) { double_ = p1; }

  public <R,A> R accept(micro.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof micro.Absyn.EDbl) {
      micro.Absyn.EDbl x = (micro.Absyn.EDbl)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
