package micro.Absyn; // Java Package generated by the BNF Converter.

public class EIdn  extends Exp {
  public final String ident_;
  public EIdn(String p1) { ident_ = p1; }

  public <R,A> R accept(micro.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof micro.Absyn.EIdn) {
      micro.Absyn.EIdn x = (micro.Absyn.EIdn)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
