package micro.Absyn; // Java Package generated by the BNF Converter.

public class Program  extends Prog {
  public final ListStm liststm_;
  public Program(ListStm p1) { liststm_ = p1; }

  public <R,A> R accept(micro.Absyn.Prog.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof micro.Absyn.Program) {
      micro.Absyn.Program x = (micro.Absyn.Program)o;
      return this.liststm_.equals(x.liststm_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststm_.hashCode();
  }


}
