package micro.Absyn; // Java Package generated by the BNF Converter.

public class SAssign  extends Stm {
  public final String ident_;
  public final Exp exp_;
  public SAssign(String p1, Exp p2) { ident_ = p1; exp_ = p2; }

  public <R,A> R accept(micro.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof micro.Absyn.SAssign) {
      micro.Absyn.SAssign x = (micro.Absyn.SAssign)o;
      return this.ident_.equals(x.ident_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.exp_.hashCode();
  }


}
