package micro.Absyn; // Java Package generated by the BNF Converter.

public class SRead  extends Stm {
  public final ListIdent listident_;
  public SRead(ListIdent p1) { listident_ = p1; }

  public <R,A> R accept(micro.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof micro.Absyn.SRead) {
      micro.Absyn.SRead x = (micro.Absyn.SRead)o;
      return this.listident_.equals(x.listident_);
    }
    return false;
  }

  public int hashCode() {
    return this.listident_.hashCode();
  }


}
