package micro.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stm implements java.io.Serializable {
  public abstract <R,A> R accept(Stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(micro.Absyn.SAssign p, A arg);
    public R visit(micro.Absyn.SRead p, A arg);
    public R visit(micro.Absyn.SWrite p, A arg);

  }

}
